# Generated by Django 2.1.7 on 2019-03-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=10)),
            ],
        ),
    ]
