# Generated by Django 2.1.7 on 2019-03-17 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0005_auto_20190317_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='username',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
