# Generated by Django 2.1.7 on 2019-03-24 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0007_auto_20190322_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetail',
            name='arrival',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightdetail',
            name='departure',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightdetail',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
