# Generated by Django 2.1.7 on 2019-03-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0008_auto_20190324_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Route', models.PositiveIntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=100, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='Route',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='flight_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_no',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
