# Generated by Django 2.1.7 on 2019-03-24 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airline3app', '0009_auto_20190324_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR', models.PositiveIntegerField(unique=True)),
                ('Date', models.DateField(null=True)),
                ('route_dest', models.CharField(max_length=100)),
                ('route_src', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(null=True)),
                ('flight_no', models.CharField(max_length=100, null=True)),
                ('username', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
