# Generated by Django 2.1.7 on 2019-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0010_fortickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortickets',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='Route',
        ),
        migrations.AddField(
            model_name='tickets',
            name='dest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='src',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ForTickets',
        ),
    ]
