# Generated by Django 2.1.7 on 2019-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0011_auto_20190324_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='arrival',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='departure',
            field=models.TimeField(null=True),
        ),
    ]
