# Generated by Django 2.1.7 on 2019-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0012_auto_20190324_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('other', 'OTHER')], default='female', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticketholders',
            name='passenger_gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('other', 'OTHER')], default='female', max_length=6),
        ),
    ]
